// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtxmCm-2hhA5wtF4zdBl9x42gSU4Tt3hM',
    appId: '1:1039511736924:web:64ff7d122e613822940c99',
    messagingSenderId: '1039511736924',
    projectId: 'flutter-auth-817ed',
    authDomain: 'flutter-auth-817ed.firebaseapp.com',
    storageBucket: 'flutter-auth-817ed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPdPmtYYHZQcnRRLedyGOfzmKcPASdd6k',
    appId: '1:1039511736924:android:cc4526e26170fc8a940c99',
    messagingSenderId: '1039511736924',
    projectId: 'flutter-auth-817ed',
    storageBucket: 'flutter-auth-817ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbd6vBC6t8tGRFtuWtMXyS9HSDtH12gZQ',
    appId: '1:1039511736924:ios:d9ca03f0911e87c8940c99',
    messagingSenderId: '1039511736924',
    projectId: 'flutter-auth-817ed',
    storageBucket: 'flutter-auth-817ed.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbd6vBC6t8tGRFtuWtMXyS9HSDtH12gZQ',
    appId: '1:1039511736924:ios:d9ca03f0911e87c8940c99',
    messagingSenderId: '1039511736924',
    projectId: 'flutter-auth-817ed',
    storageBucket: 'flutter-auth-817ed.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtxmCm-2hhA5wtF4zdBl9x42gSU4Tt3hM',
    appId: '1:1039511736924:web:54f57100efbabc18940c99',
    messagingSenderId: '1039511736924',
    projectId: 'flutter-auth-817ed',
    authDomain: 'flutter-auth-817ed.firebaseapp.com',
    storageBucket: 'flutter-auth-817ed.firebasestorage.app',
  );
}
